version: "3"

services:
  random-bg:
    image: ashoka007/random-bg-color
    ports:
      - "5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - random-bg
    ports:
      - "4000:4000"
